'use client'
import { Inter } from "next/font/google";
import { usePathname } from 'next/navigation';

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "DL Food",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isAuthOrDashboardPage = pathname.startsWith('/auth') || pathname.startsWith('/dashboard') || pathname.startsWith('/staff');
  const showHeaderAndFooter = !isAuthOrDashboardPage;

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
            <header className="padding-root border-b-2 ">{showHeaderAndFooter && <Header />}</header>
            <main className={`${showHeaderAndFooter ? 'padding-root' : ''}`}>{children}</main>
            <footer className="padding-root">{showHeaderAndFooter && <Footer />}</footer>
        </StoreProvider>
      </body>
    </html>
  );
}
